### ISSUE TITLE
sporadic IndexError

### ISSUE THREAD

**Issue by eko234** [maximbaz/restclient.kak#3]
Hi, your plugin is very cool, but from time to time I get this error:
```
Traceback (most reecnt call last):
  File "<string>", line 13, in <module>
IndexError: list index out of range
```

**Comment by max-baz** [comment]
Hi, thanks for letting me know! Does this happen with the same query, i.e. you change nothing and next time it works successfully? If so I wonder if server sends something unexpected and we are just parsing that incorrectly 🤔

**Comment by eko234** [comment]
It usually gets fixed whenever I make a change in the file and save the file, and yes it happens with the same query, even deleting a character and entering again (not changing the document structure at the end), fixes it, but repeating the query without changes just throws the same error over and over, but right now I can't test it, when I can I will try to give you more context.

Thanks.

**Comment by eko234** [comment]
My bad, the cursor just was in a commented block, when i made the change I let the cursor in the correct block and that's why it worked, the only thing that could improve would be the error message, sorry :P.

**Comment by max-baz** [comment]
Thank you for the analysis, I fixed this in the last commit 👍

**Comment by eko234** [comment]
No problem, thank you for the plugin, is really useful.
