### ISSUE TITLE
handle binary data

### ISSUE THREAD

**Issue by eko234** [maximbaz/restclient.kak#6]
Hi, today I found that your plugin doesn't handle binary data, or at least it seems so, I'm testing an endpoint that returns a pdf file, just wanted to suggest that it could be useful to provide a way to represent binary data, maybe the binary data could be saved in a tmp directory and some options could be provided to determine which programs should be used to open said data. Thanks for your work.

**Comment by max-baz** [comment]
Hello!

You are right, the current code is pretty dumb and simple:

https://github.com/maximbaz/restclient.kak/blob/e18ab7e081208e995ddcf7505b6fe04beb7a36cf/restclient.kak#L72-L77

It checks if there is any response body at all, if so it prints it to the output buffer (optionally trying to parse as JSON to prettify it, and on failure just prints the body as is). Finally the response headers are printed.

I have some good news though 😁 First, this piece of code is in Python, so should be eas(ier) to adapt. It's also a part of an option, so in principle anyone can even modify it to their specialized needs, without having to submit any changes to this repo.

Having said that, I wouldn't mind having a little smarter logic directly in this project! I don't want to over-complicate things, but I think there is a way to make a simple change and achieve what you want.

Would you like to try to submit a PR?

<details>
  <summary>Suggestion for implementation details</summary>

I propose we do something like this (pseudocode):

```python
if len(data) > 1:
    if response.headers.is_binary: # I hope there is a way to detect that we got binary response
        write(data[1], "/tmp/kak-restclient/${kak_session}.bin") # dump body as is to a hardcoded temp file - if extension is also part of response headers, you can use it instead of ".bin", up to you
       print("Binary response received, saved to /tmp/kak-restclient/${kak_session}.bin") # expand environment var - if you want to be fancy, you can also include here file info, like file size 
    else: # we keep current code as is
        try:
            print(json.dumps(json.loads(data[1]), indent=4, sort_keys=True, ensure_ascii=False), "\n")
        except:
            print(data[1])
print(data[0])
```

I'm not convinced about automatically opening files, it sounds too big of a security issue... Even if we hide it under an option, one day you'd just forget that you have this option enable, and might execute an evil request which without any indication will run an evil command on your machine...

If you convince me about it, we should just call `xdg-open /path/to/file`, it uses a standard mechanism to decide which app to open based on its type (not even file extension). But for example with pdf file, I imagine if you call the same endpoint multiple times you wouldn't want to get copy of pdf opened again and again, instead you'd probably open manually the printed path to pdf in zathura or some other viewer, and the viewer will automatically refresh the file when its updated in temp folder... So it's another reason why I don't think it should be opened automatically...

</details>

**Comment by eko234** [comment]
Oh cool, well then I could give it a shot, yes I think auto opening is dangerous, but printing that the file was saved to a certain path
seems good enough, the user could implement a command to open files under selection, indeed I think these kind of plugins
already exists, thanks for your response, I will try to submit a PR as soon as I can.

**Comment by max-baz** [comment]
Awesome! Looking forward! Don't spend too much time polishing things or making it super fancy, let's rather get some simple version first that solves your use-case, and we will iterate in the PR and agree on specifics if necessary 😉
